# Generated by Django 3.1.5 on 2021-01-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='Events')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('time', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
    ]
