# Generated by Django 3.1.5 on 2021-01-31 19:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
