# Generated by Django 3.1.5 on 2021-02-05 09:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
