# Generated by Django 3.1.5 on 2021-02-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlevelApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=900)),
                ('Date_of_birth', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('Nationaliy', models.CharField(max_length=700)),
                ('Region', models.CharField(max_length=800)),
                ('Religion', models.CharField(max_length=100)),
                ('Denomination', models.CharField(max_length=100)),
                ('Year_Of_Complilation_Form_Iv', models.CharField(max_length=50)),
                ('Name_Of_The_Secondary_School', models.CharField(max_length=600)),
                ('Your_National_Examination_No', models.CharField(max_length=200)),
                ('Division', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=100)),
                ('Points', models.CharField(max_length=100)),
                ('First_Selection', models.CharField(choices=[('PCM', 'PCM'), ('PCB', 'PCB'), ('PGM', 'PGM'), ('CBG', 'CBG'), ('HKL', 'HKL')], max_length=100)),
                ('Second_Selection', models.CharField(choices=[('PCM', 'PCM'), ('PCB', 'PCB'), ('PGM', 'PGM'), ('CBG', 'CBG'), ('HKL', 'HKL')], max_length=100)),
                ('Fathers_Name', models.CharField(max_length=700)),
                ('Father_Occupation', models.CharField(max_length=700)),
                ('Father_Number', models.CharField(max_length=700)),
                ('Mother_Name', models.CharField(max_length=700)),
                ('Mother_Occupation', models.CharField(max_length=700)),
                ('Mother_Number', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='OlevelApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=900)),
                ('Date_of_birth', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('Nationaliy', models.CharField(max_length=700)),
                ('Region', models.CharField(max_length=800)),
                ('Religion', models.CharField(max_length=100)),
                ('Denomination', models.CharField(max_length=100)),
                ('Year_Of_Complilation_Class_7', models.CharField(max_length=50)),
                ('Name_Of_The_Primary_School', models.CharField(max_length=600)),
                ('Your_National_Examination_No', models.CharField(max_length=200)),
                ('Grade', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=100)),
                ('Fathers_Name', models.CharField(max_length=700)),
                ('Father_Occupation', models.CharField(max_length=700)),
                ('Father_Number', models.CharField(max_length=700)),
                ('Mother_Name', models.CharField(max_length=700)),
                ('Mother_Occupation', models.CharField(max_length=700)),
                ('Mother_Number', models.CharField(max_length=700)),
            ],
        ),
    ]
