# Generated by Django 3.1.5 on 2021-02-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210208_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alevelapplication',
            name='Division',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=100),
        ),
        migrations.AlterField(
            model_name='olevelapplication',
            name='Grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=100),
        ),
    ]
